spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://root:s3cr3t@localhost:8888
  profiles:
    active: prod
server:
  port: 8100

user-service:
  test-value: testLocal